### ISSUE TITLE
Is the GeoJSON conformance class a mistake?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-maps#100]
We currently have a GeoJSON section in the conformance classes:

http://docs.ogc.org/DRAFTS/20-058.html#rc_geojson

Also mentioned in encodings conformance classes overview:

http://docs.ogc.org/DRAFTS/20-058.html#_overview_14

Is this a mistake or intended?

I don't think it makes sense to have a GeoJSON conformance class for Maps, as that would essentially be the same as the _OGC API - Features_ `/items` end-point.

**Comment by joanma747** [comment]
Closed in a regular telco
