### ISSUE TITLE
Convert candidate Standard from asciidoctor to metanorma asciidoc formats

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#112]
SWG session on 2023-06-07 in Huntsville, AL.

OGC Staff took an action to begin the conversion of the document to metanorma asciidoc.

**Comment by jerstlouis** [comment]
@ghobona I'm assuming this will not begin until next week, as we are planning an editing session on Friday to apply the OAB and Carl's recommendations.

**Comment by ghobona** [comment]
@jerstlouis Yes, we can start after the document goes for Public Comment.

**Comment by jerstlouis** [comment]
Addressed by #120 . Thanks @ghobona !
