### ISSUE TITLE
editorial improvements

### ISSUE THREAD

**Issue by PB-GNM** [opengeospatial/ogcapi-maps#121]
As a reaction to the call for public comment on [ogc-api-maps-part-1-core-candidate-standard ](https://www.ogc.org/requests/ogc-seeks-public-comment-on-ogc-api-maps-part-1-core-candidate-standard/), we noticed some editorial improvements.

1. Par 6.3: ”Table 2” should be “Table 3”.
2. Par 9.2.1: Table 11 is very long. One could consider putting it in an appendix.
3. Par 14.2: first bullet: A verb like “must” or “should” is missing.
4. The use of CURIE is mentioned everywhere CRS is mentioned. It would be better to bring it to one general remark for all cases.

Regards,
Pieter Bresters,
Geonovum

**Comment by joanma747** [comment]
>Par 6.3: ”Table 2” should be “Table 3”.

Issue with automatic numbers fixed

>Par 9.2.1: Table 11 is very long. One could consider putting it in an appendix.

New annex created.

> Par 14.2: first bullet: A verb like “must” or “should” is missing.

Done

> The use of CURIE is mentioned everywhere CRS is mentioned. It would be better to bring it to one general remark for all cases. 

A clarification was added in the conformance section and a note that was introduced i no longer repeated. However we still prefer to use "URL or CURIE" in many places as this is relatively new thing and we what to be precise.
