### ISSUE TITLE
How to deal with time intervals?

### ISSUE THREAD

**Issue by PB-GNM** [opengeospatial/ogcapi-maps#123]
As a reaction to the call for public comment on [ogc-api-maps-part-1-core-candidate-standard ](https://www.ogc.org/requests/ogc-seeks-public-comment-on-ogc-api-maps-part-1-core-candidate-standard/), we would like to suggest improvements on how to deal with time intervals.
Could you give answers in the document to the 2 questions below?

1.	Paragraph 14.3/14.6: With permission 6, It is not clear to the user what will happen when multiple resources are within a requested time interval. How will the user know what the actual date of the returned image is in for instance: https://maps.gnosis.earth/ogcapi/collections/sentinel2-l2a/map?center=0,51.5&scale-denominator=50000&datetime=2022-04-01/2022-05-01&width=512&height=512 ?
2.	Paragraph 14.6/14.8: How can you determine an error for not being in a domain with permission 6?

Regards,
Pieter Bresters,
Geonovum

**Comment by joanma747** [comment]
depending on the mediatype a map can be a single frame (e.g. the latest datetime on top) or a set of frames. In any case Content-datetime: response header can return one time or an interval depending on the number of "features" used to create the map.

**Comment by joanma747** [comment]
The core requirements call add the requirement of adding this Content-Datetime: 2023-01-22T0:00:00Z/2023-01-22T23:59:59Z if there is datetime in the resource.

A small note on the error conditions was added to the end of Requirements Class "Date and Time" section.
