### ISSUE TITLE
Typos and minor editorial remarks

### ISSUE THREAD

**Issue by morpl** [opengeospatial/ogcapi-maps#125]
As a reaction to request for public comment on candidate OGC API - Maps - Part 1: Core Standard (20-058):

Here is a list of typos and minor editorial suggestions/remarks that I compiled while reading the document:

- Section 6.5, p. 34, typo: "the first interval elevement" should be "the first interval element"
- Section 7.1, p. 38, typo: "The Collection Maps]," should be "The Collection Maps,"
- Section 10.3, p. 59, Recommendation 5, A, typo: "than this limit and if they to, they should" should be "than this limit and if they do, they should"
- Section 11.4, p. 68, Recommendation 9, A, ed: "The service metadata may include a minimum and maximum ...". However, only max is considered in the fragment.
- Section 11.4, p. 68, A, typo: "and if they to, they should" should be "and if they do, they should"
- Section 11.4, p. 69, C, ed: The order of C and B is unusual. 
- Section 11.4, p. 69, C, typo: "A Maps API implementation instance may specify the maximum width and height by adding a minimum property ..." - should be minimum width and height.
- Section 11.4, p. 69, C, typo: In the fragment, "minimun" should be "minimum" (twice).
- Section 13.5, p. 85, ed: There is a reference to OGC API - Features "as well as in OGC API - Common. Perhaps a single reference to Common is sufficient?
- Section 16.2.1, p. 97, ed: NOTE on CURIE is repeated several places in the document. The coloring of text in the notes varies, i.e. there are two variations.
- Section 23.2.1, p. 130, Requirement 60, A, typo: Reference to Table 10 should be to Table 12 (just the text "Table 10", the link seems fine).
- Section 24.2, p. 132, NOTE, typo: "read the the map" should be "read the map"

I would like to add that I find the document well-written and comprehensive. I think it's great work!

**Comment by joanma747** [comment]
Applied to the relevant section. Some corrections about  rec. 9 A or C,  needed to be applied in a different direction.
