### ISSUE TITLE
Service metadata: Minimum and maximum

### ISSUE THREAD

**Issue by morpl** [opengeospatial/ogcapi-maps#126]
As a reaction to request for public comment on candidate OGC API - Maps - Part 1: Core Standard (20-058):

Section 11.4, p. 69, Recommendation 9, C:
How about adding maximum in the same way as minimum? 
And default values as well?

**Comment by joanma747** [comment]
minimum was mistake and will be replaced by maximum in 9, C and removed minimum from 9, A
