### ISSUE TITLE
HTTP status code 204 or 404

### ISSUE THREAD

**Issue by morpl** [opengeospatial/ogcapi-maps#127]
As a reaction to request for public comment on candidate OGC API - Maps - Part 1: Core Standard (20-058):

Several places in the document, it is said that the HTTP status code will be "204 or 404".

I'm concernced that no clear distinction between using 204 and 404 in implementations can cause problems in the interaction between clients and servers. That is, clients could treat responses very differently based on 2xx or 4xx, and different server implementations could perhaps use 204 or 404 for the same situation with respect to data.

On the one hand, I can see that one can argue to use 404 for an empty response since it is the result of a combination of parameters set by the client that yields no data. On the other hand, given that 4xx indicates client errors, I would expect that an empty response due to lack of data in the area has 204. And I would expect 404 when I'm using a wrong path and try to access a non-existing dataset.

Requirement 27 (/req/datetime/subset-definition) D reads "If the intervalOrPoint values fall entirely outside the range of
valid values defined for the identified axis, a 204 or 404 status code SHALL be returned".
And Requirement 32 (/req/general-subsetting/subset-definition) D reads "If the intervalOrPoint values fall entirely outside the range of valid values defined for the identified axis, a 204 status code SHALL be returned."
So at least this seems inconsistent with the of "204 or 404" elsewhere.

**Comment by joanma747** [comment]
We will add 404 in Req 32. The 204 does not allow returning a body so many implementation prefer 404. So we will consistently allow for both.
