### ISSUE TITLE
Globe Color vs. "void" Color

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-maps#128]
While working on our DGGS stuff, I was wondering if perhaps it would make sense to sneak in an extra parameter in the "Background" requirement class.

The bgcolor parameter normally refers to how the map gets painted where there is no data.

But what about making a distinction where the projection itself says nothing will ever be rendered there?

For example with the ISEA projection ( https://maps.gnosis.earth/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/map?crs=OGC:1534 ):

![map](https://github.com/opengeospatial/ogcapi-maps/assets/5140074/9ced27c5-64fe-4d3f-8025-3db9c4d1943d)

you could have one background color for the triangles of the icosahedron, and another color for the rest of the map.

This applies to several other projections with interruptions or points "falling off the globe" like stereographic, ortographic, Mollweide or Goode homolosine.

It does not apply to cylindrical projections like Mercator where the poles are at infinity and you can wrap around the longitude.

It also applies in 6DOF 3D perspective projection where you could pick a different background colors for the "sky" vs. the "globe".
And of course it applies well to Arctic and orthographic projections as well.

**Comment by joanma747** [comment]
This is done by adding void-color and void-backgroud as new requirements in the backgroup conformance class.
