### ISSUE TITLE
Annex B example links possibly missing ampersand

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#129]
Discussed during the March 27, 2024 session in Delft.

The Annex B example links possibly missing ampersand.

https://raw.githubusercontent.com/opengeospatial/ogcapi-maps/master/core/standard/annex_examples.adoc

https://docs.ogc.org/DRAFTS/20-058.html#_d63fd55e-47f4-4a06-8c28-8fa36f0b6d4b

**Comment by jerstlouis** [comment]
The issue seems to only affect the HTML rendering, and not the PDF.

This should probably be fixed in metanorma, since it is simply an HTML link automatically generated.

In ASCIIDoc, `&` are supposed to automatically be replaced by `&amp;` when converting to HTML.
Perhaps there is an issue related to links specifically?

**Comment by ghobona** [comment]
Thanks @opoudjis !

@jerstlouis Could you please check the links and confirm that you are happy with how they are rendering?

I will also do the same.

**Comment by opoudjis** [comment]
Please wait until release to check. The Metanorma release for this should have been tonight, but Google Fonts have changed their API, so the release it held up until we update Fontist to deal with it. I'm assuming it will be tomorrow.

**Comment by ghobona** [comment]
@jerstlouis Please check all of the URLs in Annex B, especially the ones in Annex B.7.

They look fine to me, although the ones in B.7 do not appear to be 'clickable' in HTML but are 'clickable' in the PDF.

**Comment by jerstlouis** [comment]
@ghobona In 892a662857a8ffbba0630fa56753de689a71ccb7 you made this change:

```diff
-https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=%5BEPSG:4326%5D["https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=[EPSG:4326\]"]
+//https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=%5BEPSG:4326%5D["https://maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=[EPSG:4326\]"]
+
+&#x68;&#x74;&#x74;&#x70;&#x73;&#x3A;//maps.gnosis.earth/ogcapi/collections/blueMarble/map?center=0,51.5&scale-denominator=20000000&crs=&#x5B;EPSG:4326&#x5D;
```

Can we go back to the original now, maybe that will fix the clickability in HTML?

**Comment by ghobona** [comment]
@jerstlouis @opoudjis I have returned the URLs to their original form.

The Pull Request is https://github.com/opengeospatial/ogcapi-maps/pull/132

The HTML build completes successfully but the PDF breaks.

When I comment out the URLs in B.7 the PDF build completes successfully.

@opoudjis Could you please look into what is causing the PDF build to break when the compiler reaches the URL in B.7?

**Comment by opoudjis** [comment]
I'm sorry about the delay in responding, but I'm up to my knees in refactoring for a different project...

**Comment by ghobona** [comment]
@jerstlouis I have now merged Pull Request https://github.com/opengeospatial/ogcapi-maps/pull/132

@opoudjis I still need confirmation of why the compiler breaks when it reaches B.7.

**Comment by ghobona** [comment]
@opoudjis Please note that @jerstlouis and I have just tested the build on his computer and confirmed that both the HTML and PDF documents are built successfully.
