### ISSUE TITLE
More complex format negotiation for getFeatureInfo and the mapFormat

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-maps#20]
WE proposed to use info?f=text/html&mapFormat=image/png

In WCS for the multipart formats, they are experimenting with a format negotiation like this:
Accept: text/html; mapFormat=image/png

Does it make sense in our case? 

The multitile request is also affected:
Accept: application/x-zip-compressed; tileFormat=image/png

**Comment by jerstlouis** [comment]
It seems that the use case would be addressed by negotiation by profile (See https://github.com/opengeospatial/ogcapi-common/issues/8).
The use case for HTML map formats is not really important, since implementations are free to do pretty much anything.
