### ISSUE TITLE
Prepare Draft Charter

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#27]
On 2020-06-04 the SWG passed the following [motion](https://portal.ogc.org/files/?artifact_id=93454):

* The WMS SWG approves the re-chartering of the WMS SWG as the OGC API – Maps SWG.

Related to https://github.com/opengeospatial/OGC-API-Tiles/issues/34#issuecomment-641190127

**Comment by ghobona** [comment]
@joanma747 

The charter has had a detailed review and multiple edits. See PR https://github.com/opengeospatial/OGC-API-Maps/pull/28

Next week, during the OGC Member Meeting, I will put forward a Motion to approve the draft Charter internally within the SWG and to submit the draft Charter to the TC Chair (@ogcscotts).

**Comment by ghobona** [comment]
2020-07-09 SWG telecon: There was no objection to asking the TC Chair to start the TC vote as soon as the Architecture DWG endorsement vote ends on 2020-07-10.

**Comment by ghobona** [comment]
2020-07-13. Three-week TC review ends on 2020-08-03.

**Comment by ghobona** [comment]
- [ ] TC: There's a typo on page 2, ' decribe infromation' should be `describe information`

- [ ] TC: Add definition of map from [OGC 06-042](http://portal.opengeospatial.org/files/?artifact_id=14416)

**Comment by joanma747** [comment]
WE have a charter
