### ISSUE TITLE
"cascaded" parameter

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ogcapi-maps#38]
The current draft of "OGC API Maps Tiles" recommends that the "map description response" include a boolean property called "cascaded", whose value is described thusly:

> 0 means that the collection maps have not been retransmitted another map service or API. A positive number indicates how many times the collection map has been retransmitted. 

I don't see the point in such a property.  Its meaning is ambiguous and unreliable, and its value is irrelevant.  It originated in the early WMS specifications when cascading maps from service to service was a bold new endeavour, and some felt that there might be some value in indicating the number of hops that a map takes.  But I think that twenty years of nobody getting any value out of this property has shown us its uselessness.

**Comment by joanma747** [comment]
I inclined to agree with you.

It there is no objection, we will consider this parameter finally "deprecated" and we will remove it from the OGC API for the reasons stated above.

**Comment by ghobona** [comment]
I completely agree.

**Comment by jerstlouis** [comment]
Can we close this issue?

**Comment by joanma747** [comment]
Yes
