### ISSUE TITLE
Add a path to the legend for each map

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#44]
As demonstrated by @pomakis during the July 2020 sprint there are a number options for adding a path to a legend.

**Comment by jerstlouis** [comment]
I think with the current design this would rather be handled by OGC API - Styles.
See https://github.com/opengeospatial/ogcapi-styles/issues/16 and https://github.com/opengeospatial/ogcapi-styles/issues/36.
Can we close this issue here?

**Comment by joanma747** [comment]
There is #97 to get a embedded legend in a map. To get the legend alone will require the styles API that will be synchronize in OGC API map extension.
