### ISSUE TITLE
Do we need a spatial extent for each CRS that the server supports

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#45]
For example, see below.

```json

{
  "crsSpatialExtents": [
    {
      "bbox": [
        -180,
        -90,
        180,
        90
      ],
      "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
    },
    {
      "bbox": [
        -20037508.3427892,
        -20037508.3427892,
        20037508.3427892,
        20037508.3427892
      ],
      "crs": "http://www.opengis.net/def/crs/EPSG/0/3395"
    }
]
}
  

```

**Comment by bradh** [comment]
This could rapidly get out of hand (e.g. if the server has a full EPSG data set, it'll be thousands of entries). Suggest keeping it to a required entry (e.g. CRS84) and allowing clients to reproject it if needed.

**Comment by jerstlouis** [comment]
This is a good question... In Coverages I [suggested](https://github.com/opengeospatial/ogcapi-coverages/issues/129) that one could add a query parameter to `/coverage/domainset` to retrieve the domainset in a CRS different than the storageCRS.

I think at minimum we would need to advertise the extent in the storageCRS in the collection description.
`storageCRSExtent` or similarly named property?

**Comment by joanma747** [comment]
We agreed that listing every CRS will be too verbose. Instead the real "limits" of the extent are defined by the stored "stuff".

Done for storageCRS in Requirement Classes "Geospatial Data Map" and "Dataset Map":

```
"storageCrsExtent": {
    "spatial" : {
         "bbox" : [ [ 47736, 4421022, 797736, 4734022 ] ]
    }
  },
```
