### ISSUE TITLE
Add these link relations to the spec

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#48]
Let's use this Issue to capture the link relations that are being proposed.

For each, please provide the label and description.

Also state the source and the target.

**Comment by pomakis** [comment]
I see at least the following map-and-tile-specific link relations.  The rel suggestions are my own suggestions, which I'm providing for discussion.

For each of the rel values (other than the IANA-standard), we should probably qualify them somehow (e.g., "ogc:maps:thumbnail").

```
  target resource type:
      a map-description document
  example endpoints:
      {landingPage}/map
      {landingPage}/collections/{collectionId}/map
  typical sources:
      a dataset-level landing page
      a collection description (e.g., {landingPage}/collections/{collectionId})
  suggested rel:
      "map" (or perhaps "mapDescription")

  target resource type:
      a map (possibly subsetted with query parameters)
  example endpoints:
      {landingPage}/map/{styleId}
      {landingPage}/collections/{collectionId}/map/{styleId}
  typical sources:
      a map-description document
  suggested rel:
      "styledMap" (or perhaps "map")

  target resource type:
      a list of available tilesets
  example endpoints:
      {landingPage}/tiles
      {landingPage}/map/{styleId}/tiles
      {landingPage}/collections/{collectionId}/map/{styleId}/tiles
      {landingPage}/collections/{collectionId}/tiles
  typical sources:
      a dataset-level landing page
      a collection description
      a map-description document
  suggested rel:
      "tileSets"

  target resource type:
      a tileset (providing tile-URL templates, etc.)
  example endpoints:
      {landingPage}/map/{styleId}/tiles/{tileMatrixSetId)
      {landingPage}/collections/{collectionId}/map/{styleId}/tiles/{tileMatrixSetId)
      {landingPage}/collections/{collectionId}/tiles/{tileMatrixSetId)
  typical sources:
      a list of available tilesets
  suggested rel:
      "tileSet"

  target resource type:
      a tile
  example endpoints:
      .../tiles/{tileMatrixSetId)/{tileMatrix}/{tileRow}/{tileCol}.png
  typical sources:
      a tileset
  suggested rel:
      "tile" (or perhaps "mapTile" and "dataTile") (templated=true)

  target resource type:
      a legend graphic
  example endpoints:
      {landingPage}/map/{styleId}/legend
      {landingPage}/collections/{collectionId}/map/{styleId}/legend
      .../tiles/{tileMatrixSetId)/{tileMatrix}/legend
  typical sources:
      a map-description document
      a tileset
  suggested rel:
      "legend" (or perhaps the IANA-standard "icon")

  target resource type:
      a thumbnail image
  example endpoints:
      {landingPage}/map/{styleId}/thumbnail
      {landingPage}/collections/{collectionId}/map/{styleId}/thumbnail
  typical sources:
      a map-description document
  suggested rel:
      "thumbnail" (or perhaps the IANA-standard "preview")
```

**Comment by jerstlouis** [comment]
The _Tiles_ relation types are being taken care of: https://github.com/opengeospatial/NamingAuthority/issues/167

This leaves us with:

- Link to a map (I think we have settled for the obvious `"rel" : "http://www.opengis.net/def/rel/ogc/1.0/map")
- A _map-description_ document -- possibly this is not required for Core and we have mostly removed this from the specification, with the possibility that additional metadata may be potentially re-introduced if they end up being necessary
- _Legend_ (also discussed in styles: https://github.com/opengeospatial/ogcapi-styles/issues/16 https://github.com/opengeospatial/ogcapi-styles/issues/36 and #44)
- _Thumbnail_

**Comment by jerstlouis** [comment]
We no longer have the _map-description_ document.

**Comment by jerstlouis** [comment]
Currently the [link relation types recommendation in Core conformance class](https://github.com/opengeospatial/ogcapi-maps/blob/master/core/standard/recommendations/core/REC_link-relation-type.adoc) specifies `icon` for legend. I don't think this (_Refers to an icon representing the link's context._) is descriptive enough of what a legend is, it is not an icon for the map (although it may use icons to represent symbology).

So I suggest we change this to `http://www.opengis.net/def/rel/ogc/1.0/legend`.
Then we would need to add:

- http://www.opengis.net/def/rel/ogc/1.0/legend
- `stylesheet` (IANA, to link to a style sheet document)
- `preview` (IANA, for map thumbnail)

to [5.2 Link Relations](http://docs.ogc.org/DRAFTS/20-058.html#_link_relations) already lists most of the link relation types used by the specification.

**Comment by joanma747** [comment]
Transfered to the NA in a new issue.
