### ISSUE TITLE
Should OGC API - Maps use the 'crs' or 'bbox-crs' parameter?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#49]
At least one other specification uses 'bbox-crs' . So should OGC API - Maps use the 'crs' or 'bbox-crs' parameter?

**Comment by jerstlouis** [comment]
Can we close this issue? If not already applied, this is covered by #82.

**Comment by jerstlouis** [comment]
This issue has been addressed by #82 which has been applied and closed.
