### ISSUE TITLE
Clarify Filter and CQL usage

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#51]
Work is on-going in OGC API - Features SWG developing an extension for Filtering and CQL.

The Filtering and CQL extension will, at a later stage, be [moved](https://github.com/opengeospatial/ogcapi-features/issues/423#issuecomment-668057132) into OGC API - Common.

There's a need to discuss how a future extension of OGC API - Maps could support a similar Filtering and CQL capability.

Please coordinate with the OGC API - Features SWG on this topic.

**Comment by pvgenuchten** [comment]
this relates to a question which came up in a ogc-api-records implementation discussion, we have a usecase that we want to draw a single feature on a map (the bounds of a record item), we do not know in advance the bounds of this feature, so we would not like to provide the bounds of the requested map representation, only crs, width, height and record-id:
/collections/{col}/map/{style}?crs=4326&width=200&height=200&id=aaa-bbb-ccc

the implementation would find the item, and 'zoom' to the relevant area around the geometry of the requested item

(id is one of the queryable parameters in oapif and oapir)

Could this case fit in this specification?

**Comment by joanma747** [comment]
I believe this one fits better:

/collections/{col}/items/aaa-bbb-ccc/map/{style}?crs=4326&width=200&height=200

We are making BBOX optional, and it depends on the situation, the write BBOX should be determined by what is more "natural" to do.
BUT
We need to know the bbox of the response or the client will not be able to overlap the feature on top of other layers.
This could be done by:
A: /collections/{col}/items/aaa-bbb-ccc/map/ could tell you about that
B: /collections/{col}/items/aaa-bbb-ccc/map/{style}?crs=4326&width=200&height=200 will return a header with this info.

**Comment by pvgenuchten** [comment]
Indeed, requiring to advertise the image bounds is a valid argument, the response header approach is interesting, does it fit with ogc api common concepts?

**Comment by ghobona** [comment]
**2020-12-10 Cross SWG discussion**

* The design of the Filtering and CQL extension supports the use case of retrieving a selection of features from layer.
* The approach needs to be able to support BBOX. 
* An HTTP response header that contains the BBOX of the response could address the need to able to present details of the BBOX. If you do not specify the BBOX in the request, the server should respond with the BBOX in the HTTP response header.
* Resolution: No changes are needed to the Filter and CQL extension. The Maps API needs to consider rendering results of filters.
* If you are asking for PNG, you are not necessarily asking for something that is georeferenced. So there are cases where there is no need for that.
