### ISSUE TITLE
Visualizing the payload from an implementation of OGC API - Features or the EDR API

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#53]
Could a future extension of OGC API -  Maps be used to request  a visualized payload from an implementation of OGC API - Features or the EDR API?

This could be something like the OGC API equivalent of the [Feature Portrayal Service](http://portal.opengeospatial.org/files/?artifact_id=13186&version=2).

Perhaps it would be more appropriate to implement it as a future extension of OGC API - Processes?

Please coordinate this discussion with:

* EDR API SWG
* OGC API - Processes SWG

**Comment by jerstlouis** [comment]
This is also very much of the focus of _OGC API - Processes - Part 3: Workflows & Chaining - Collection Input_ conformance class (which could be e.g., an OGC API collection available as Features and/or Coverages, and Processes - Part 3 - collection output conformance class where the output could also a be an OGC API collection accessible as OGC API - Maps or OGC API - (Map) Tiles, and  the concept of a well-known _RenderMap_ Process as described in #42.

Can we close this one and continue the discussion in Processes - Part 3 for generic Collection Input/Output, and in #42 for aspects specific to a maps rendering well-known process?

**Comment by joanma747** [comment]
There is a way to do this described in issue #42. Decided to close in regular telco.
