### ISSUE TITLE
Handling of default style at multi-collection /map endpoint

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ogcapi-maps#54]
As a follow-up up to the recent "OGC API - Maps" sprint (and the related gitter discussion at https://gitter.im/opengeospatial/OGC-API-Sprint-July-2020), CubeWerx's multi-collection map-description endpoint at

https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/map?f=json

now returns a metadata document that provides links to the available map/{styleId} endpoints, etc.

However, there are two issues with this metadata document that need to be resolved.

### Issue 1

The client needs to know which collections are compatible with which style, both so that it will know what it's going to get back for a particular style in the absence of a geodata parameter, and so that it will know what collections can be requested (via a geodata parameter) for a particular style.

We addressed this by introducing a "compatibleCollections" field per style.  E.g.,

```
  "compatibleCollections": [
    "AgricultureSrf",
    "CulturePnt",
    "CultureSrf",
    ...
  ]
```

Does this seem like a reasonable approach?

### Issue 2

Dealing with the concept of a default style is tricky.  The default style can be different for each collection, so it doesn't have a single definition.  This wouldn't really be an issue if a server was prohibited from having an actual style called "default", but there's no such prohibition.  For example, our test implementation has a style called "default", and it's defined only for the Daraa_mosaic_2019 collection.  This leads to the problem that the style entry:

    {
      "id": "default",
      ...
    }

is ambiguous, or at least awkwardly overloaded.

There needs to be some entry for the default style, since there needs to be a link to the map/default endpoint.  But how does one do this without conflating it with a style with an actual ID of "default"?

There's also the issue of what style a map/default request invokes for a collection that has a style called "bob" and a style called "default", where the style called "bob" is flagged as being the default style.  This seems like a silly situation, but there's nothing prohibiting it.

This could all be resolved if the "OGC API - Styles" specification prohibited the definition of a style with an ID of "default", but I'm not very comfortable with such a prohibition.  Then again, it would make all of these issues go away... What do others think?

What we've done in the meantime is introduce a "defaultStyle" field that provides the link to the map/default endpoint.  It would also be the logical place for links to the map/default/legend and map/default/info endpoints, etc.  But I'm not sure that this is the right approach.

**Comment by jeffharrison** [comment]
On Issue 1... seems like a reasonable approach.

It's likely some will want a link to the schema of the collection, but that seems a bit like overkill imho...

Regards,
Jeff

**Comment by pomakis** [comment]
I've changed how we resolve issue 2.  The links for requesting things with the default style are now reported in the "styles" array with all of the other styles, but with an style ID of "default".  This set of links doesn't include links to the style definition (i.e., stylesheets), because every collection may have a different default style.

If there happens to be an actual style with an ID of "default", it's not reported in the "styles" array, other than via the entry representing the default style.

Our test service at https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa has been updated to reflect this.  To highlight the issue of having a style with an ID of "default", this service has such a style, defined only for the Daraa_mosaic_2019 collection.

I think this is a reasonable way of reporting links for requesting things with the default style, and a reasonable way of handling the resulting clash if there happens to be a style with an ID of "default".

Another option would be to forbid styles with an ID of "default", but I hesitate to make that a requirement, since it would introduce an incompatibility with existing styles that may already have that ID.

**Comment by jeffharrison** [comment]
Seems rational... it's also helpful to see working examples!

Perhaps we could get this on the agenda for an upcoming meeting?

Regards,
Jeff

**Comment by jerstlouis** [comment]
@pomakis Is this issue / proposal still relevant with the more recent work?

Now the dataset and collections would have a link to a `/styles` page linking each individual style supported, and from within that list of styles would be links for retrieving a map e.g.

https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/styles?f=json&pretty=true
https://maps.ecere.com/ogcapi/collections/Daraa/styles?f=json

**Comment by pomakis** [comment]
Things have changed a lot since I first opened this issue.  However, I still see the need for some sort of "compatibleCollections" field in the description of a style.

E.g.: https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/styles/Topographic?f=json&pretty=true

**Comment by jerstlouis** [comment]
@pomakis We have suggested the _GeoDataClass_ concept for this purpose:

https://github.com/opengeospatial/NamingAuthority/issues/97
https://github.com/opengeospatial/ogcapi-styles/issues/13

Both the style and the collection can specify URIs that can be used to determine compatibility, and at that URI one can find the schema of what can be found in/what can be used for styling a collection.

The nice thing is that this extends beyond a single service, informing whether styles and collections are compatible across different end-points.
It can also be used for collections compatible as inputs to processes.

**Comment by jerstlouis** [comment]
@pomakis Can we close this issue and continue the discussion on compatible collections in the context of the [GeoDataClasses](https://github.com/opengeospatial/NamingAuthority/issues/97) concept?

**Comment by joanma747** [comment]
We believe that if you use the \map endpoint you do not care about what style or collection you will get.

If you use \style\light\map (or \style\night\map), then \style\light (or \style\night) will tell you what collections are supported by the style. This is because in OGC API maps the style comes first (in opposition to what happened in WMS)

Each collection may also have styles specific to them (example: \collections\buildings\style\light). 
GeoDataClasses (https://github.com/opengeospatial/styles-and-symbology/issues/12) is a mechanism in styles metadata as well as in collections (future) and in tileset metadata (currently)

No  action required in the current draft. Decided in regular telco.
