### ISSUE TITLE
REC_link-relation-type not included in spec

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#55]
The Maps description includes properties describing the maxHeight, maxWidth, minScaleDenominator and maxScaleDenominator.

The properties are mentioned in a [Recommendation](https://github.com/opengeospatial/OGC-API-Maps/blob/master/core/standard/recommendations/core/REC_link-relation-type.adoc) and the [OpenAPI definition document](https://github.com/opengeospatial/OGC-API-Maps/blob/master/openapi/swaggerhub/maps.yaml). However, it appears that the Recommendation is not linked to from the spec. 

Mentioned on [Gitter](https://gitter.im/opengeospatial/OGC-API-Sprint-July-2020?at=5f2bcbf293579d2e34616dc5).

**Comment by jerstlouis** [comment]
It is still true today that the [REC_link-relation-type.adoc](https://github.com/opengeospatial/OGC-API-Maps/blob/master/core/standard/recommendations/core/REC_link-relation-type.adoc) file is not included in the specification. 

minScaleDenominator / maxScaleDenominator shows up in the Table 15.

**Comment by joanma747** [comment]
In the issue https://github.com/opengeospatial/ogcapi-maps/issues/86, there is a suggestion to add maxWidth and max Height (with a different name) in the service metadata (so at the service level). Obviously, OGC API maps implementations can use OpenAPI "maximum" to declare the width and height parameter maximum directly.

The issue on where to define minScaleDenominator and maxScaleDenominator at the collection level persists and I'm not sure we agreed on a solution.

**Comment by jerstlouis** [comment]
@joanma747 We have already [applied](http://docs.ogc.org/DRAFTS/20-058.html#_service_metadata_2) the suggestion to add the limits at the service metadata level, including the 'maxPixels' (width * height) option. Compiled generic clients don't like to / don't want to parse OpenAPI documents, so this is not redundant with the OpenAPI definition.

We can define minScaleDenominator / maxScaleDenominator as extended properties for the collection description resource (we have _minScaleDenominator_ and _minCellSize_ on [our server](https://maps.ecere.com/ogcapi/collections/blueMarble?f=json)).

**Comment by joanma747** [comment]
@jerstlouis. About maxWidth, nice that we did that. However, this ignores our discussion that if we add a "x-OGC-limits" this is for any limits for any OGC API so maxWidth should be mapMaxWidth as proposed in #86

**Comment by jerstlouis** [comment]
@joanma747 ​`maxWidth` is inside a `maps` object inside `x-OGC-limits` though, so it is specific to maps?
See [Recommendation 7](http://docs.ogc.org/DRAFTS/20-058.html#_service_metadata_2).

**Comment by joanma747** [comment]
Ok. Makes sense. I'll make sure this is consistent along the current draft and close issue #86
