### ISSUE TITLE
Maps Overview on ogcapi.org is outdated

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-maps#75]
The overview page on ogcapi.org is very outdated and misguiding.

The README.md overview section of this repo is already more up to date.

**Comment by jerstlouis** [comment]
2021-07-29 SWG: @ghobona will file an issue with the infrastructure office to update ogcapi.org _Maps_ overview to the latest overview on this GitHub repo.

**Comment by joanma747** [comment]
@ghobona I believe the status of this page: https://ogcapi.ogc.org/maps/overview.html has not changed in a year. The main Readme.md in GitHub is better.

/map/{styleId} should be /{styleId}/map

....

**Comment by joanma747** [comment]
Please take the content of the overview section in readme.md (https://github.com/opengeospatial/ogcapi-maps/#overview
) up to before "conformance classes" and replace what is in https://ogcapi.ogc.org/maps/overview.html
