### ISSUE TITLE
Move partitioning conformance classes to Part 1 & add `subset` query parameter

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-maps#76]
Suggesting that:
- bbox,
- subset,
- map tiles

be separate conformance classes, but all defined in _Part 1_ (they are currently in https://github.com/opengeospatial/ogcapi-maps/tree/master/extensions/partitioning/standard).

This would reflect the fact that `bbox` is a basic capability that most implementations will want to implement, yet allow implementers to achieve conformance with _Core_, and only implement the partitioning mechanisms that they care to support initially.

**Comment by joanma747** [comment]
We accepted this proposal in the OGC MM 120.

**Comment by joanma747** [comment]
WE should implement this in the document structure in github.
