### ISSUE TITLE
Proposed addition to service metadata

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-maps#86]
New Recommendation.
A. The service metadata response linked in the landing page (rel type service-meta) should include the following properties: limits.mapsMaxWidth and limits.mapsMaxHeight being mapsMaxWidth the maximum width that server is willing to return to the client, and maxHeight the maximum height that server is willing to return to the client. 
B. The implementation should offer a JSON representation of the service metadata.

**Comment by jerstlouis** [comment]
We have added the limits to the [service metadata](http://docs.ogc.org/DRAFTS/20-058.html#_service_metadata_2).

Can we close this issue now?

**Comment by joanma747** [comment]
Final decision is to include this limits in `x-OGC-limits.maps.maxWidth`, `x-OGC-limits.maps.maxHeight` and `x-OGC-limits.maps.maxPixels` in the service meta.
