### ISSUE TITLE
Should we move the scaling functionality to OGC API - Maps - Part 1

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#91]
Since [OGC API - Tiles - Part 1](http://docs.ogc.org/DRAFTS/20-057.html) will support the partitioning of maps, why don't we move the Scaling functionality from the draft [OGC API - Maps - Part 2](https://github.com/opengeospatial/ogcapi-maps/tree/master/extensions/partitioning/standard) to the draft [OGC API - Maps - Part 1](https://github.com/opengeospatial/ogcapi-maps/tree/master/core)?

**Comment by joanma747** [comment]
Effectively, it was moved to the Part 1 some time ago but for some reason we forgot to remove it from the extension folder. I have done this now. Sorry for the confusion and thanks.
