### ISSUE TITLE
Ability to specify Projection Center

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-maps#92]
In projections like stereographic (of which Arctic Polar Stereographic and Antarctic Polar Sterographic are examples with specific projection centers), it is desirable to use a projection center close to the view center.

There currently is no mechanism to specify such a variable projection center other than by providing a full projection definition (which might not be supported by Part 1: Core -- only by URI / reference).

A challenge is that the resulting CRS would not have a URI to return (in CRS response header), since the projection center of the original CRS was overridden. On one hand this introduces complexity, on the other it can result in a maps more appropriate for the selected area, especially in projections like a stereographic projection.

**Comment by jerstlouis** [comment]
Examples of projections where a particular projection center include Oblique Stereographic (EPSG:9809), Lambert Azimuthal Equal Area (EPSG:9820), Orthographic (EPSG:9840). An orientation could be specified as well.

How could an API support these conveniently? I don't see these EPSG codes in http://www.opengis.net/def/crs/EPSG/0, so I imagine it is because they are not CRS per se, but projections.

Would we need a _projections_ OGC registry as well? There are definitions for ellipsoids, datums, and coordinate systems, but I cannot find these projections EPSG code on the definition server.

Then we could have a map request like:

```
   .../map?
      projection=[epsg-projection:9840]&
      projection-center=Lat(40),Lon(-120)&
      orientation=40
```

NOTE: I included `-projection` because we said for CURIEs that _if  `-{objectType}` is missing, the default object type is crs_. It would be nice if we can do without it...

@desruisseaux Your CRS expertise would be most welcome here. Any thoughts on this approach?

If I understand correctly, ISO 19111 conceptually does support defining CRS hierarchy with a base projection, for which a center and orientation could then be specified separately.

I imagine this is essentially defining a custom CRS in an ad-hoc manner.
The `Content-Crs:` response header could perhaps then be a CRS JSON/PROJJSON object in this case?

I believe this is an important use case for _OGC API - Maps_, which is moving away from dynamic maps to focus more on static maps and print cartography. On the other hand, I wouldn't expect this functionality to be used together with Map Tiles. Instead dynamic maps can use geographic data with variable width TMS and re-project / re-orient on the fly in the client.

@joanma747 This is our very last issue that needs thoughts / discussions  :) It would be nice to have gone through them all before the sprint, where tons of new ones will magically appear :) It would make for an interesting discussion topic at the sprint as well.

**Comment by jerstlouis** [comment]
@ghobona @rob-metalinkage Do we have a registry of _projections_ in the definition server (e.g., `EPSG:9840`)? Thanks.

**Comment by desruisseaux** [comment]
[OGC Web Map Service (WMS)](https://portal.ogc.org/files/?artifact_id=14416) §6.7.3.4 defines CRS in "AUTO2" namespace as a syntax of the form "`AUTO2:` _projection_, _factor_, _longitude_, _latitude_". Projection codes defined in annex B are (no relationship with EPSG codes):

|Code  | Projection                      |
|------|---------------------------------|
|42001 |WGS 84 / Auto UTM                |
|42002 |WGS 84 / Auto Tranverse Mercator |
|42003 |WGS 84 / Auto Orthographic       |
|42004 |WGS 84 / Auto Equirectangular    |
|42005 |WGS 84 / Auto Mollweide          |

So for example `AUTO2:42003,1,-100,45` is an orthographic projection centred on 100°W and 45°N. There is no stereographic code yet, but I see no reason to not add it. Maybe orientation could be added as an optional parameter. Note that there is currently no way to use a datum other than WGS84.

On the topic or OGC registry for projection, this is called "Operation Method" in ISO 19111 terminology. This registry exists in https://epsg.org and I guess could be reflected on OGC server. For referencing an EPSG object unambiguously, the EPSG code is not sufficient. We need the specify the kind of object (CRS, datum, etc.) as well. OGC we used to define a syntax for that, the [Definition identifier URNs in OGC namespace](https://portal.ogc.org/files/?artifact_id=24045) (OGC tends to favor HTTP URL instead of URN, but I still find URN more human-readable). Table 2 lists 23 object types, including `crs`, `axis`, `method` and `parameter`. So for example:

* `urn:ogc:def:crs:EPSG::3395` is the _"WGS 84 / World Mercator"_ projected CRS.
* `urn:ogc:def:method:EPSG::9804` is the _"Mercator (variant A)"_ operation method used by above CRS.
* `urn:ogc:def:parameter:EPSG::8801` is the _"Latitude of natural origin"_ parameter used by above operation method.
* `urn:ogc:def:parameter:EPSG::8802` is the _"Longitude of natural origin"_ parameter used by above operation method.
* _etc._
* Note that `urn:ogc:def:crs:EPSG::8801` is _"NAD83 / Alabama East + NAVD88 height"_. So it is important to specify the kind of object (CRS versus parameter) when using an EPSG code.

In WKT2 specification (ISO 19162), it is recommended to rely on EPSG codes for parameters instead of their name, because there is too much risk that a parameter name such as "Latitude of natural origin" is named differently on different implementations ("Latitude", "lat0", "Latitude of centre", etc.).

I suppose that parameter codes could be used for building something like below (I wonder if `"urn:ogc:def`" could or should be omitted for brevity in this context):

```
.../map?
    baseCRS=urn:ogc:def:crs:EPSG::4326&
    projection=urn:ogc:def:method:EPSG::9804,
               urn:ogc:def:parameter:EPSG::8801=40,
               urn:ogc:def:parameter:EPSG::8802=-120
```

**Comment by jerstlouis** [comment]
Thank you very much @desruisseaux for the prompt feedback.

> On the topic or OGC registry for projection, this is called "Operation Method" in ISO 19111 terminology. This registry exists in https://epsg.org/ and I guess could be reflected on OGC server.

Ah, yes thank you, I see 9840, 9820, 9809 are already all there at http://www.opengis.net/def/method/EPSG/0 .

About URNs vs URIs, the [recent policy](https://docs.opengeospatial.org/pol/09-048r6.html#toc14) on Compact URIs (CURIEs) allows us to use safe CURIEs. The `-method` in `[epsg-method:9840]` (that I had called _-projection_) would already specifically refer to the EPSG operation method 9840. 

A key goal here is simplicity and intuitiveness, so I am hoping we can take some liberty in _OGC API - Maps_ to specifically define parameters such as `projection`, `projection-center` and `orientation`, ending up up with something more like:

```
   .../map?
      projection=[epsg-method:9840]&
      projection-center=Lat(40),Lon(-120)&
      orientation=40
```

Requirements in the specification would clearly explain how to apply the _orientation_ and _projection-center_ parameters for different projections.

I hope this is not swaying away too unreasonably far from ISO 19111 :)

**Comment by desruisseaux** [comment]
I was not aware of the new http://www.opengis.net/def/method/ space, thanks for pointing that out. Indeed it can be useful.

On the parameter names, I wonder if there is a risk of adding confusion if we invent new names. For example for the Stereographic projection, the same parameter already has all the following names:

* EPSG: Latitude of natural origin
* OGC: `latitude_of_origin`
* ESRI: `Latitude_Of_Origin`
* NetCDF: `latitude_of_projection_origin`
* GeoTIFF: `NatOriginLat`
* PROJ: `lat_0`

For some other projections the name is "latitude of false origin", or "latitude of centre", etc. Those differences in names are not random; they carry a difference in what the parameter means. If we nevertheless want some simple names, the ones defined in §10.6.1 of [OGC 01-009](https://portal.ogc.org/files/?artifact_id=999) are in wide use. For a more complete list the [GeoTIFF projections list](http://geotiff.maptools.org/proj_list/) seems to reflect common usages. So for stereographic projection it would be:

* `latitude_of_origin`
* `central_meridian`

**Comment by jerstlouis** [comment]
@desruisseaux the idea is to have a single, intuitive, readily understood by non-experts `projection-center` parameter, and explain in requirements to what it should map in the different projections.

In dynamic 2D cartographic maps with runtime re-projection, it is a tyical concept to have a "projection center" which is following your "view center" (`center` in _OGC API - Maps_, which would default automatically to `projection-center` if `center` is not specified separately) as you pan around the map.

The requirements would explicitly map the `Lon()` value of `projection-center` to the _central meridian_, and the `Lat()` value to the _latitude_of_origin_.

> On the parameter names, I wonder if there is a risk of adding confusion if we invent new names. For example for the Stereographic projection, the same parameter already has all the following names:

I don't see how one single simple name applying to both latitude and longitude, for all projections, can add further confusion to this already existing soup of names ;) Au contraire...

> Those differences in names are not random; they carry a difference in what the parameter means.

They might carry a subtle differences, but there is almost always a clear mapping to the projection center.
A counter-example where it would be ambiguous which latitude or longitude parameter should be considered for the projection center would be useful (most likely one where neither _central meridian_ nor _latitude of origin_ is defined).

The [PROJ documentation](https://proj.org/usage/projections.html) says  that `+lat_0` (_Latitude of origin_) and `+lon_0` (_Central meridian_) can be applied to most coordinate system definitions.

Thank you!

**Comment by desruisseaux** [comment]
When the projection has _"False Easting"_ or _"False Northing"_ parameter, then there is an ambiguity about whether the projection centre, i.e. the (0,0) coordinates, is before of after the easting/northing offset. I suspect that it may be the difference between  _"Latitude of natural origin"_ and _"Latitude of false origin"_  (but I didn't verified).

Some EPSG projections (e.g. "Lambert Cylindrical Equal Area", "Mercator (variant A)", "Popular Visualisation Pseudo Mercator", "Polar Stereographic (variants B and C)") do not have a "central latitude" parameter, but only a "latitude true scale" parameter with a very different effect. How should we define "central latitude" in those cases?

**Comment by jerstlouis** [comment]
This link is very useful:

https://sis.apache.org/tables/CoordinateOperationMethods.html#9804

Difficult to find the valid parameters for methods anywhere else.

> How should we define "central latitude" in those cases?

Actually, according to that SIS link, the parameter is also called _Latitude of natural origin_ `[epsg-parameter:8801]` for Mercator (variant A). For Polar Stereographic B and C, it is called _Latitude of standard parallel_.
 We could potentially provide an ordered  list of operation parameters to which the projection center latitude and longitude are mapped in the requirement, e.g.:

The `projection-center` `Lat` value SHALL be mapped to the first matching operation parameter available for the selected operation method of the `projection` query parameter, in this order:
- [epsg-parameter:8801] _Latitude of natural origin_ (PROJ: _lat_0_ or _lat_ts_)
- [epsg-parameter:8811] _Latitude of projection center_ (PROJ: _lat_0_)
- [epsg-parameter:8832] _Latitude of standard parallel_ (PROJ: _lat_0_)
- [epsg-parameter:8823] _Latitude of first standard parallel_ (PROJ: _lat_1_)

The `projection-center` `Lon` value SHALL be mapped to the first matching operation parameter available for the selected operation method of the `projection` query parameter, in this order:
- [epsg-parameter:8802] _Longitude of natural origin_ (PROJ: _lon_0_)
- [epsg-parameter:8812] _Longitude of projection center_ (PROJ: _lon_0_)
- [epsg-parameter:8833] _Longitude of origin_ (PROJ: _lon_0_)

> When the projection has "False Easting" or "False Northing" parameter, then there is an ambiguity about whether the projection centre, i.e. the (0,0) coordinates, is before of after the easting/northing offset.

From what I understand of the proj explanations of [operation latitude parameters here](https://proj.org/development/reference/cpp/operation.html):

> **Latitude of natural origin/Center Latitude**
>    _The latitude of the point from which the values of both the geographical coordinates on the ellipsoid and the grid coordinates on the projection are deemed to increment or decrement for computational purposes. Alternatively it may be considered as the latitude of the point which in the absence of application of false coordinates has grid coordinates of (0,0)._
> **Latitude of projection centre**
>    _For an oblique projection, this is the latitude of the point at which the azimuth of the central line is defined._
> **Latitude of false origin**
>    _The latitude of the point which is not the natural origin and at which grid coordinate values false easting and false northing are defined._
> **Latitude of standard parallel**
>    _For polar aspect azimuthal projections, the parallel on which the scale factor is defined to be unity._

The _latitude of false origin_ is a point **different** from the projection center which corresponds to the false origin. Therefore, I think there is no direct correspondance between the _latitude of false northing_ and the projection center i.e., the _Latitude of natural origin / Ceneter latitude_ must still be specified or default to some value separately. For _OGC API - Maps_, I think the main use case is visualization / portrayal, and the `center` query prameter allows us to center on the portion of the map of interest, so I don't think the false easting / northing will be particularly useful.

For projections with e.g., multiple standard parallels, I think to be useful one would need more control over the additional parameters. For those cases in particular, I think it would be useful to define the ability to unambiguously set any projection parameters with a syntax like:

_Lambert Conic Conformal (2SP) example_
```
   .../map?
      projection=[epsg-method:9802]&
      projection-center=Lon(-120)&
      projection-parameters=[epsg-parameter:8823](-40),[epsg-parameter:8824](-90)&
      orientation=40
```

**Comment by joanma747** [comment]
We decided that we will add a conformance class that will become an alternative to crs=

we will allow this set of parameters: 

crs-datum=[epsg-datum:6326]
crs-proj=[epsg-method:9840]
crs-proj-param=[epsg-parameter:8823](40),[epsg-parameter:8824](90)
crs-proj-center=Lat(...),Lon(...)
crs-orientation=40   (we are forcing it in degrees)

(
there could be a:

crs-wkt=
but we will not describe this in the standard (yet).
)

The crs-proj-center Lat value SHALL be mapped to the first matching operation method parameter available for the selected operation method of the projection query parameter, in this order:

[epsg-parameter:8832] Latitude of standard parallel (PROJ: lat_ts)
[epsg-parameter:8823] Latitude of first standard parallel, if only a single standard parallel can be set i.e., no [epsg-parameter:8824] parameter is available (PROJ: lat_ts)
[epsg-parameter:8801] Latitude of natural origin (PROJ: lat_0 )
[epsg-parameter:8811] Latitude of projection center (PROJ: lat_0)

The crs-proj-center Lon value SHALL be mapped to the first matching operation method parameter available for the selected operation method of the projection query parameter, in this order:

[epsg-parameter:8802] Longitude of natural origin (PROJ: lon_0)
[epsg-parameter:8812] Longitude of projection center (PROJ: lon_0)
[epsg-parameter:8833] Longitude of origin (PROJ: lon_0)

**Comment by joanma747** [comment]
I understand, these "crs-*" params replaces the "crs=" param.
Do we need to apply all this stuff to the bbox-crs? and to the other places where we have it (e.g. centre-crs...)? There will be an explosion of parametres!

**Comment by jerstlouis** [comment]
> Do we need to apply all this stuff to the bbox-crs? and to the other places where we have it (e.g. centre-crs...)? There will be an explosion of parametres!

No :)

The common / easy thing to do for a client is to simply use center=lon,lat (default CRS84 `center-crs`), scale-denominator= and width and/or height for the desired map dimension, not having to deal at all with the coordinate values in that custom CRS.

Potentially what we could do is define a special value that refers to the output crs (whether specified by `crs=` or this custom projection CRS) for use by `bbox-crs`, `center-crs` and `subset-crs` e.g., `bbox-crs=output-crs` or `bbox-crs=output`, or if a special CRS URI from WMS already exists for this purpose.

A couple related questions are:
- how do we describe the custom projection CRS in the response header, and
- are the coordinate values actually well defined based on those `crs-` parameters? (e.g., units etc.)
- if I recall correctly, we said the orientation is applied _after_ the CRS, so the orientation value should have no impact on how the coordinate values are interpreted for subset/bbox (if the output CRS is used for those). The rules on how subsetting work together with orientaiton may need to be clarified, in terms of should extra content be shown if it fits the map viewport, and does the entire bbox have to always returned for all orientations. If subsetting by center + width/height, the orientation would change the 'bbox' that is subset in that output CRS due to returning a square map corners falling on a different place.

**Comment by joanma747** [comment]
We realize that we need 

- a list of supported items (methods+parameters, datums)
- some headers that will complement (e.g. add content-orientation) or replace the "content-crs" header
- a description of the response
