### ISSUE TITLE
Link diagram for maps

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-maps#94]
Trying to imitate this diagram from the OGC API tiles (https://github.com/opengeospatial/ogcapi-tiles/blob/master/core/standard/images/relMapTiles.png) I came up with an equivalent diagram for maps.

Please note that only "text files" can expose links easily (there are actually link headers but we do not use them) so "map" is an end-node and, even if we have map-tiles, they need to be exposed as links from the "collection" or the "landing page" directly and not from maps. In other words, the links structure does not reflect the path structure.

Let's see if we agree on this and we can add it as an illustration in the standard draft.

![image](https://user-images.githubusercontent.com/5230444/187250616-20314b7c-6df5-4e68-9d99-8e599e68938b.png)

**Comment by jerstlouis** [comment]
@joanma747 We do have rel: map directly in our styles array see e.g.,

https://maps.ecere.com/ogcapi/collections/Daraa/styles?f=json

Makes sense to just stick to "tilesets list" to focus on Maps in this diagram.

**Comment by joanma747** [comment]
>@joanma747 We do have rel: map directly in our styles array see e.g.,
Good. Should this part of the styles API?, or there is no harm in showing it in maps anyway?

**Comment by jerstlouis** [comment]
@joanma747 I think it belongs more here in _Maps_ than in _Styles_ in fact.
Maps is what defines the `map` link relation and we demonstrate the use case that you can use it from a Landing Page (common-1), Collection (common-2), or Style (Styles-1).

**Comment by joanma747** [comment]
Illustration added to the overview section.
