### ISSUE TITLE
Syntax for styled maps

### ISSUE THREAD

**Issue by jonblower** [opengeospatial/ogcapi-maps#99]
I haven't been involved in this effort before, but I read the [draft standard](http://docs.ogc.org/DRAFTS/20-058.html). One thing I found a bit surprising was the syntax for styled maps, e.g.: 

- `/map/` for maps in the default style
- `/styles/{styleId}/map/` for maps in another style

I'm not clear why the style is part of the URL's path, not part of its query string (as it was in WMS)? It feels unnatural to make the style part of the implied resource hierarchy, and it seems a bit unnecessary to have two different URL paths for the same resource (the map) depending on whether it's in the default style or not.

**Comment by jerstlouis** [comment]
@jonblower The idea is that you can get a _map_ from some existing geospatial resource, which could be e.g., a dataset as a whole, a collection, or a style.

_OGC API - Maps - Part 1: Core_ does not support clients submitting a custom style with which to a render a map.

The `/styles/{styleId}/map` end-point allows to retrieve a map from existing end-points defined by [OGC API - Styles](https://github.com/opengeospatial/ogcapi-styles).

A mechanism for this would be an extension and #42 is a proposal for how this could work, leveraging concepts of _Well-Known processes_ (e.g., a _RenderMap_ process with specific inputs) and _OGC API - Processes - Part 3: Workflows & Chaining_, and possibly an equivalent functionality directly at `/map` supporting POSTing the same content (an execution request referencing OGC API collections and styles).

**Comment by jonblower** [comment]
Thanks @jerstlouis. I'm new to this but struggling a bit to grasp the idea. A style isn't a geospatial resource, so how would you get a map from it? I would think that you get the map from the dataset/collection, but apply a style.

**Comment by jerstlouis** [comment]
@jonblower Well, the style may be offered as part of an OGC API dataset publication with multiple collections (`/styles/{styleId}` alongside `/collections`), in which case a map of that style would show a map including all or some of those collections, or as part of an individual collection (`/collections/{collectionId}/styles/{styleId}`), where a map of that style will only render that one collection.

A pure _Styles API_ with no data is also possible (e.g., a styles repository), in which case a map of that style is either not offered or uses some kind of default / showcase data.

**Comment by jonblower** [comment]
Thanks for the helpful examples. I think I get the idea now, but I still find the design a bit unexpected. I can see how a server might advertise `/styles` as well as `/collections`, but it still seems strange to me to use `/collections/x/styles/y/map` as the URL to a styled map. Personally I'd still go for `/collections/x/map?style=y`, closer to the WMS spec. Maybe just a matter of taste as both approaches work technically of course.

**Comment by jonblower** [comment]
Thanks @jerstlouis and @joanma747 - I can see from the linked issues that you've already discussed this in the core group, who have agreed on the current approach. Feel free to close this issue as it doesn't seem like it's up for further discussion.

**Comment by jerstlouis** [comment]
Thank you for the feedback @jonblower . We may need to clarify the idea in the spec to make it more self-explanatory.

Keep in mind that a `style` query parameter building block could still be defined later (e.g., in an extension) if we find out that there is an important need for it.
